name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      ssh:
        image: linuxserver/openssh-server
        ports:
          - 2222:2222
        env:
          USER_NAME: testuser
          PASSWORD_ACCESS: false
          PUBLIC_KEY_DIR: /keys
          SUDO_ACCESS: false
          LOG_STDOUT: true
        volumes:
          - ./keys:/keys:ro
          - ./repo:/repo
        options: >-
          --health-cmd "ps aux | grep sshd"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Wait for SSH service to become healthy
        run: sleep 10

      - name: Run tests
        run: go test ./...
